
using System.Diagnostics;

namespace ProjectEuler {
    class Problem2 {
        public static string Name() {
            return "Even Fibonacci Numbers";
        }

        public static string Description() {
            string val = "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:";
            val += "/n";
            val += "/n";
            val += "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...";
            val += "/n";
            val += "/n";
            val += "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";
            return val;
        }

        public string Answer() {
            Stopwatch sw = new Stopwatch();
            sw.Start();

            double num1 = 1, num2 = 2, fibonacci = 3, total = 2;

            do {
                if (fibonacci % 2 == 0) {
                    total += fibonacci;
                }

                num1 = num2;
                num2 = fibonacci;
                fibonacci = num1 + num2;
            } while (fibonacci < 4000000);

            sw.Stop();
            return globalMethods.DisplayAnswer(total.ToString(), sw);
        }
    }
}
